version: '3.8'

services:
  backend:
    build:
      context: ../AURA-Back-End/AuraBackend
      dockerfile: Dockerfile
    container_name: aura_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../AURA-Back-End/AuraBackend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../AURA-Back-End/AuraBackend/.env
    depends_on:
      - db
    networks:
      - aura_network

  frontend:
    build:
      context: ../AURA-Front-End
      dockerfile: Dockerfile
    container_name: aura_frontend
    volumes:
      - ../AURA-Front-End/src:/usr/share/nginx/html
      - ../AURA-Front-End/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - aura_network

  db:
    image: pgvector/pgvector:pg16
    container_name: aura_db
    environment:
      POSTGRES_DB: auraDb
      POSTGRES_USER: auraUser
      POSTGRES_PASSWORD: naruto77
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aura_network

volumes:
  pgdata:


networks:
  aura_network:
    driver: bridge
